[workspace]
members = ["crates/*"]

[workspace.dependencies]
# publish = true
loxide_parser = { version = "0.1.0", path = "crates/loxide_parser" }
# publish = false
insta = { version = "1.31.0", features = ["glob"] }
thiserror = { version = "1.0.44" }
